#ifndef WEB_SERVER_H
#define WEB_SERVER_H

#include <Arduino.h>

void setupWebServer();
void handleWebClients();
bool checkAuthentication();
void handleRoot();
void handleSetup();
void handleManageActions();
void handleManageOS();
void handleCSS();
void handleJS();
void handleCommand();
void handleScript();
void handleJiggler();
void handleStatus();
void handleGetWiFi();
void handleSetWiFi();
void handleScan();
void handleListScripts();
void handleSaveScript();
void handleLoadScript();
void handleDeleteScript();
void handleListQuickActions();
void handleSaveQuickAction();
void handleDeleteQuickAction();
void handleReorderQuickActions();
void handleListCustomOS();
void handleSaveCustomOS();
void handleDeleteCustomOS();
void handleListQuickScripts();
void handleSaveQuickScript();
void handleDeleteQuickScript();
void handleManageScripts();
void handleTrackpadFullscreen();

#endif //WEB_SERVER_H
